server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${DB_URL:localhost:5432/postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:2514}
  jpa:
    generate-ddl: true
    show-sql: false